name: echo
on:
  workflow_call:
    inputs:
      echo-value:
        required: true
        type: string
jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: echo
        run: |
          echo ${{ github.event.head_commit.committer.name }} 
          echo ${{ github.event.head_commit.committer.username }} 
          echo ${{ github.event.head_commit.committer.email }} 
          echo "hello"
