name: echo
on:
  workflow_call: {}

jobs:
  test-action:
    runs-on: ubuntu-latest
    env:
      ECHO: "SET ME"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: echo
        run: |
          echo ${{ env.ECHO }}
