name: my-test-action
on:
  push: {}

jobs:
  test-action-1:
    uses: ./.github/workflows/echo.yaml
    with:
      echo-value: "hello"
    
  test-action-2:
    uses: ./.github/workflows/echo.yaml
    with:
      echo-value: "world"
